language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - oracle-java8-installer
script:
- xvfb-run npm test
